name: Ally Palanzi
markdown: kramdown
exclude: ["node_modules", "gulpfile.js", "package.json", "project_template.psd"]
permalink: pretty
post_dirs: false
description: "ally palanzi's portfolio"
url: http://allypalanzi.com
