name: Ally Palanzi
markdown: kramdown
highlighter: rouge
exclude: ["node_modules", "gulpfile.js", "package.json"]
permalink: /:title.html
post_dirs: false

description: 'a blog about code, design, & life'
url: http://blog.allypalanzi.com
